### ISSUE TITLE
Add metamask compatible key

### ISSUE THREAD

**Issue by okwme** [ChainSafe/ethermint-deploy#1]
The Cosmos-SDK hardcodes the level of entropy for generating new keys which results in a mnemonic phrase of 24 words. Until this phrase length can be passed in a flag ([open issue](https://github.com/cosmos/cosmos-sdk/issues/4278#issuecomment-549070624)) you are unable to easily import the ethermint account into metamask. There is a workaround where you generate the mnemonic phrase somewhere else and then pass it as a recover flag.

Might be cool to demonstrate this by replacing the following line:
```sh
echo "testpass" | emintcli emintkeys add mykey
```
with this modified line that uses the default truffle mnemonic phrase:
```sh
(echo "1234567890"; echo "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat") | emintcli keys add mykey --recover
```

**Comment by okwme** [comment]
ahhh, i see now that the `emintcli keys` command doesn't have the `--recover` option ;_;

**Comment by austinabell** [comment]
cosmos keys functionality will be available with https://github.com/ChainSafe/ethermint/pull/147

**Comment by okwme** [comment]
LGTM
