### ISSUE TITLE
Error in Deploying contract

### ISSUE THREAD

**Issue by blockchain-app12** [ChainSafe/ethermint-deploy#4]
`$ yarn start
yarn run v1.19.1
$ node ./web3/deploy_contract.js
Compiling contract code...
Unlocked account address: 	 0xDe547715a81BB7d664554336cBB4BD9DAc0431c4
Deploying contract...
Error: Returned error: authentication needed: password or unlock
    at Object.ErrorResponse (/home/devel-sultana/cosmosProject/ethermint-deploy/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/devel-sultana/cosmosProject/ethermint-deploy/node_modules/web3-core-requestmanager/src/index.js:140:36`

**Comment by austinabell** [comment]
I don't mean to assume the issue but there was some changes with the genesis commands in Ethermint, the readme is updated. Check the commands run to make sure that the commands ran without an error, and make sure you restart the web3 server whenever you restart the chain, or just don't delete the data directory with the command `rm -rf ~/.emint*` and manage exactly what you need to change manually

**Comment by austinabell** [comment]
If you restart the node with new keys and don't restart the server with the new key, the key that will be retrieved will not be the one unlocked on the server.
